### PR TITLE
Use half of cores available on machine.

### PR DESCRIPTION
**Pull request by retrohacker**
Ceiling function for integer division

### CODE REVIEW

**Comment by rvagg** [comment]
fine by me, after you merge, trigger a docker hub rebuild, and wait for it to complete do this:

1. put the config entries into .ssh/config listed here: https://github.com/iojs/build/tree/master/setup/containers#readme
2. run this:

```
ssh ssh iojs-build-containers-1 docker pull -a iojs/build
ssh ssh iojs-build-containers-2 docker pull -a iojs/build
```

at the moment I think I'm favouring manual updates rather than setting up a hook for docker hub because it'll mean changing docker hub each time we privision new hosts and updating hopefully won't be a frequent exercise.

**Comment by retrohacker** [comment]
double `ssh` intentional?

**Comment by rvagg** [comment]
2 servers

**Comment by retrohacker** [comment]
Ah, I mean double on the same line: `ssh ssh iojs-build...`

**Comment by rvagg** [comment]
hah, no, not sure what that's about, just one will do

**Comment by bnoordhuis** [comment]
The assumption is that `make` is GNU make, right?  And the intention of this PR is to not consume all cores in case there is more than one build running?  Wouldn't it be better in that case to use `-l <loadavg>` instead of `-j <jobs>`?  Something like `make -l $(getconf _NPROCESSORS_ONLN)` allows for burst-y behavior when the machine is otherwise unoccupied.

**Comment by rvagg** [comment]
@bnoordhuis I'd defer to you on the wisdom of this, I generally consider loadavg akin to voodoo but if you think this is a better approach then perhaps we should give it a go

**Comment by bnoordhuis** [comment]
I've had good results with it.  The rule of thumb I use is that the requested load average should not be more than the number of processors.  It's okay if those processors are hyperthreaded because compilation is normally memory bandwidth-constrained enough that it doesn't matter.

**Pull request merged**
